### ISSUE TITLE
React Router version notes in coding assignment 1.9

### ISSUE THREAD

**Issue by ElijahMSmith** [Code-the-Dream-School/react#4]
A student in the Dove react class made a note that the programming assignment 1.9 requires the use of the `exact` property for each Route component. This was removed in v6 of React Router, which most students will likely be using. I've made a few edits to the assignment markdown file in the Wiki that should help clarify this:

[Lesson-1.9.md](https://github.com/Code-the-Dream-School/react/files/11709458/Lesson-1.9.md)

As an additional note, it appears that React Router is part of lesson 2.1, not 1.9 as it is marked on the Wiki. I'm not sure if this is intentional and it doesn't REALLY matter since there is not textbook content on React Router, but I wonder if there is a better way to note this.

**Comment by mamooredesigns** [comment]
Thank you for this, Eli!  Big help!  I've made the changes and also added a note in the Learning Objective to clarify that React Router is a third-party library and they'll be learning more about it in the following lesson.  I'm open to other suggestions if there are better/additional ways to help clarify that point for students.
