### ISSUE TITLE
React Course Suggestion - Lesson 5.1 Stretch Goal

### ISSUE THREAD

**Issue by Jkuffler** [Code-the-Dream-School/react#5]
Currently we need to refresh the browser in order to _sort new tasks_ by date. What can we do to have a new task automatically sorted when added?  Using the hooks already imported/in place: how would you update the code so the app's state changes with the new task?

**Comment by mamooredesigns** [comment]
Thanks, @Jkuffler!  Just updated that wiki page to include the stretch goal and the state hint.
